# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

let
  # Options for BTRFS mounts
  opts = [
    "space_cache=v2"
    "discard=async"
    "noatime"
  ];
  # Paths for RAID devices
  r1Path = "/dev/sda3"; # needed due to unknow problems when using /dev/disk/by-uuid/ for system raid while booting process
  r2Path = "/dev/disk/by-uuid/";
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # System mounts
  fileSystems."/" = {
    device = r1Path;
    fsType = "btrfs";
    options = [ "subvol=@" "compress=zstd:1" ] ++ opts;
  };

  fileSystems."/nix" = {
    device = r1Path;
    fsType = "btrfs";
    options = [ "subvol=@nix" "compress=zstd:1" ] ++ opts;
  };

  fileSystems."/home" = {
    device = r1Path;
    fsType = "btrfs";
    options = [ "subvol=@home" "compress=zstd:1" ] ++ opts;
  };

  fileSystems."/var/log" = {
    device = r1Path;
    fsType = "btrfs";
    options = [ "subvol=@log" "compress=zstd:1" ] ++ opts;
  };

  # Raid 1 mounts

  # Raid 2 mounts

  # Boot and firmware partitions
  fileSystems."/boot" = {
    device = "/dev/sda2";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/boot/firmware" = {
    device = "/dev/sda1";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
