# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

let
  opts = [
    "degraded"
    "space_cache=v2"
  ];
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/r1";
    fsType = "btrfs";
    options = [ "subvol=@" ] ++ opts;
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-label/r1";
    fsType = "btrfs";
    options = [ "subvol=@nix" ] ++ opts;
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-label/r1";
    fsType = "btrfs";
    options = [ "subvol=@home" ] ++ opts;
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-label/r1";
    fsType = "btrfs";
    options = [ "subvol=@log" ] ++ opts;
  };

  fileSystems."/boot" = {
    device = "/dev/sda2";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/boot/firmware" = {
    device = "/dev/sda1";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
